spring:
#  batch:
  #  job:
  #    enabled: false
  #    jdbc:
  #      initialize-schema: always
  datasource:
    password: spring
    jdbc-url: jdbc:postgresql://localhost:5432/spring_batch
    username: spring
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: create-drop
  universitydatasource:
    password: spring
    jdbc-url: jdbc:postgresql://localhost:5432/university
    username: spring
